/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonComponent: typeof import('./src/components/components/ButtonComponent.vue')['default']
    ComponentPanel: typeof import('./src/components/ComponentPanel.vue')['default']
    EditorCanvas: typeof import('./src/components/EditorCanvas.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FormComponent: typeof import('./src/components/components/FormComponent.vue')['default']
    ImageComponent: typeof import('./src/components/components/ImageComponent.vue')['default']
    InputComponent: typeof import('./src/components/components/InputComponent.vue')['default']
    PropertyPanel: typeof import('./src/components/PropertyPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextComponent: typeof import('./src/components/components/TextComponent.vue')['default']
  }
}
